config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
 resources :users do
    resource :profile
  end
  resources :contacts
  get '/about' => 'pages#about'
  root 'pages#home'

end

app/models/contact.rb
class Contact < ActiveRecord::Base
   validates :name, presence: true
   validates :email, presence: true
end

app/models/plan.rb
class Plan < ActiveRecord::Base
   has_many :users
end

app/models/profile.rb
class Profile < ActiveRecord::Base
    belongs_to :user
    
# class Profile < ActiveRecord::Base
#   validates :name, presence: true
# end
 
# Person.create(name: "John Doe").valid? # => true
# Person.create(name: nil).valid? # => false
    
    
# class Profile < ActiveRecord::Base
#     validates :points, numericality: true
#     validates :games_played, numericality: { only_integer: true }
# end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :plan
  attr_accessor :stripe_card_token
  def save_with_payment
    if valid?
      customer = Stripe::Customer.create(description: email, plan: plan_id, card: stripe_card_token)
      self.stripe_customer_token = customer.id
      save!
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?
  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :stripe_card_token, :email, :password, :password_confirmation) }
    end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
    def new
        @contact = Contact.new
    end
    
    def create
        @contact = Contact.new(contact_params)
    
        if @contact.save
            name = params[:contact][:name]
            email = params[:contact][:email]
            body = params[:contact][:comments]
            
            ContactMailer.contact_email(name, email, body).deliver
            flash[:success] = "Message Sent."
            redirect_to new_contact_path
        else
            flash[:danger] = "Error Occured, message was not sent."
            redirect_to new_contact_path
        end
    end

    private
    def contact_params
       params.require(:contact).permit(:name, :email, :comments) 
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
        @basic_plan = Plan.find(1)
        @pro_plan = Plan.find(2)
    end
    
    def about
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  
  def new
    # form where a user can fill out their own profile.
    @user = User.find( params[:user_id] )
    # @profile = @user.build_plan
    @profile = Profile.new
  end
  
  def create
    @user = User.find( params[:user_id] )
    @profile = @user.build_profile(profile_params)
    if @profile.save
      flash[:success] = "Profile Updated!"
      redirect_to user_path( params[:user_id] )
    else
      render action: :new
    end
  end
    
  private
    def profile_params
      params.require(:profile).permit(:first_name, :last_name, :job_title, :phone_number, :contact_email, :description)
    end  
end

app/controllers/users/registrations.controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  def create
    super do |resource|
      if params[:plan]
        resource.plan_id = params[:plan]
        if resource.plan_id == 2
          resource.save_with_payment
        else
          resource.save
        end
      end
    end
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  
  before_filter :select_plan, only: :new
  
  def create
    super do |resource|
      if params[:plan]
        resource.plan_id = params[:plan]
        if resource.plan_id == 2
          resource.save_with_payment
        else
          resource.save
        end
      end
    end
  end
  
  private
  def select_plan
    unless params[:plan] && (params[:plan] == '1' || params[:plan] == '2')
      flash[:notice] = "Please select a membership plan to sign up."
      redirect_to root_url
    end
  end
  
  
end

app/controllers/users/users_controller.rb
class UsersController < ApplicationController
  
  # def create
  #   @profile = User.build_profile
  # end
  
  def show
    @user = User.find( params[:id] )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/contacts/new.html.erb
<!--Contact Page File-->
<style>
    img {
	margin-left: auto;
    margin-right: auto;
    width: 60%;  
	padding: 2px;
	margin: 30px;
	border: 7px solid orange;
}

#SubmitButton {
    margin-left: auto;
    margin-right: auto;
    width: 100%;  
    position: relative;
    bottom: -12px;
    padding: 0px;
    
}

.well {
    margin-left: auto;
    margin-right: auto;
    width: 95%;  
    min-height: 21px;
    padding: 28px;
    margin-bottom: 20px;
    background-color: #788DFF;
    border: 1px solid #e3e3e3;
    border-radius: 8px;
    -webkit-box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.05);
    box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.05);
}

</style>

<div class="text-center">
<h1><u>Contact Form</u></h1>
</div>

<div class="row">
    <div class="col-md-4 col-md-offset-4">
        <div class="well">
            <%= form_for @contact do |f| %>
                <div class="form-group">
                    <%= f.label :name %>
                    <%= f.text_field :name, class: 'form-control' %>
                </div>
                
                <div class="form-group">
                    <%= f.label :email %>
                    <%= f.email_field :email, class: 'form-control' %>
                </div>
                
                <div class="form-group">
                    <%= f.label :comments %>
                    <%= f.text_area :comments, class: 'form-control' %>
                </div>
                <div id = "SubmitButton" class="form-group actions">
                <%= f.submit 'Submit', class: 'btn btn-warning btn-lg btn-block' %>
            <% end %>
        </div>
    </div>
</div>

<div class ="text-center">
    <img src="http://thumbnails.hulu.com/13/747/59927_512x288_generated__kBczNxdJEkS-YCMKRwTLVQ.jpg">
</div>
 <!--"col-xs-6 col-md-4"-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Konoha Boogie</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag "https://js.stripe.com/v2/", type: 'text/javascript' %>
  <%= javascript_include_tag 'application' %>
  <%= tag :meta, :name => "stripe-key", :content => STRIPE_PUBLIC_KEY %>
  <%= csrf_meta_tags %>
  
  <link rel="apple-touch-icon" sizes="57x57" href="/apple-icon-57x57.png">
  <link rel="apple-touch-icon" sizes="60x60" href="/apple-icon-60x60.png">
  <link rel="apple-touch-icon" sizes="72x72" href="/apple-icon-72x72.png">
  <link rel="apple-touch-icon" sizes="76x76" href="/apple-icon-76x76.png">
  <link rel="apple-touch-icon" sizes="114x114" href="/apple-icon-114x114.png">
  <link rel="apple-touch-icon" sizes="120x120" href="/apple-icon-120x120.png">
  <link rel="apple-touch-icon" sizes="144x144" href="/apple-icon-144x144.png">
  <link rel="apple-touch-icon" sizes="152x152" href="/apple-icon-152x152.png">
  <link rel="apple-touch-icon" sizes="180x180" href="/apple-icon-180x180.png">
  <link rel="icon" type="image/png" sizes="192x192"  href="/android-icon-192x192.png">
  <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
  <link rel="icon" type="image/png" sizes="96x96" href="/favicon-96x96.png">
  <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
  <link rel="manifest" href="/manifest.json">
  <meta name="msapplication-TileColor" content="#ffffff">
  <meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
  <meta name="theme-color" content="#ffffff">
</head>

<body>

<nav class="navbar navbar-default navbar-static-top" role="navigation">
  <div class='container'>
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-nav-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_path, class: 'navbar-brand' do %>
        <i class= "fa fa-users"></i>
        Konoha Boogie Home
        <% end %>
    </div>
    <div class="collapse navbar-collapse" id="main-nav-collapse">
      <div class="nav navbar-nav navbar-right">
        <% if current_user %>
          <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: 'btn btn-primary navbar-btn' %>
        <% else %>
          <%= link_to "Log In", new_user_session_path, class: 'btn btn-primary navbar-btn', method: :get %>
          <!--<%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-success navbar-btn', method: :get %>-->
        <% end %>
      </div>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Contact Us", new_contact_path %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div>
</nav>

<div class = 'container'>
    <% flash.each do |key, value| %>
    <%= content_tag :div, value, class: "alert alert-#{key}" %> 
    <% end %>
    
  <%= yield %>
</div>

</body>
</html>

app/views/pages/about.html.erb
<style>
    img {
	margin-left: auto;
    margin-right: auto;
    width: 100%;  
	/*text-align: center;*/
	/*display: inline;*/
	/*position: relative;*/
	/*right: 20px;*/
    }

    p {
    text-align: center;
    font-size: 24px;
    font-family: arial;
    }
    
    h1 {
    text-align: center;
    text-decoration: underline;
    }
</style>

<h1 class= "text-center"><strong>About Us</strong></h1>
<p>We are dedicated to finding great connections for all of our Gennin, Chuunin, and Jounin's who just feel like
there is more to life than ninjustsu. There is a whole world of internet and wonder at waiting at their fingertips!</p>

<div class= "text-center">
<img src="http://img08.deviantart.net/7e05/i/2013/284/7/f/naruto_sage_mode_by_guardianmo-d6q1966.png" width="854" height="1494">
</div>

app/views/pages/home.html.erb
<!DOCTYPE Html>
<head>
    <title>SaaS afrass</title>    
</head>

<style>

img {
    margin-left: auto;
    margin-right: auto;
    width: 100%;
    position: relative;
    top: 10px;
    right: 17px;
    padding: 2px;
    margin: 20px;
    border: 7px solid orange;
}    

.btn-lg, .btn-group-lg > .btn {
    margin-left: auto;
    margin-right: auto;
    width: 100%;  
    padding: 10px 16px;
    font-size: 24px;
    line-height: 1.33;
    border-radius: 6px;
}

#CreateProfile {
    margin-left: auto;
    margin-right: auto;
    width: 35%;  
    padding: 10px 16px;
    font-size: 24px;
    line-height: 1.33;
    border-radius: 6px;
}

</style>

<body>

<div id ="CreateProfile" class= "btn btn-success btn-lg">
<%= link_to "Create your Profile!", new_user_profile_path(current_user) if current_user %>
</div>

<div class="jumbotron text-center">
    <h1>Welcome to Konoha Boogie!</h1>
    <h3>A membership website where ninjas can meet web developers</h3>
    <h4>忍者は、 Web開発者を満たすことができる会員制サイト</h4>
</div>

<div class="row">
    <div class= "col-md-6">
    <h2 class="text-center">Basic Membership</h2>
    <h4>Sign up for Free, and get basic access to our growing community!</h4>
    <%= link_to "Sign up with Basic", new_user_registration_path(plan: @basic_plan.id), class: 'btn btn-info btn-lg btn-block' %>
    </div>
    
    <div class= "col-md-6">
    <h2 class="text-center">Pro Membership</h2>
    <h4>Subscribe for only $10/month, and get contact information & perks!</h4>
    <%= link_to "Sign up with Pro", new_user_registration_path(plan: @pro_plan.id), class: 'btn btn-warning btn-lg btn-block' %>
    </div>
</div>

<div class="text-center">
    <img src="http://4.bp.blogspot.com/-xcC8sAn9afg/UQQ02BL3GaI/AAAAAAAAKds/eGixb4wawHg/s1600/konoha-wallpapers10.jpg">
</div>





</body>

app/views/profiles/new.html.erb
<!--This new.html.erb file is for the Profiles to store user profiles in.-->
<!--< %@variable% >-->
<style>
.well {
    margin-left: auto;
    margin-right: auto;
    width: 95%;  
    min-height: 21px;
    padding: 28px;
    margin-bottom: 20px;
    background-color: #788DFF;
    border: 1px solid #e3e3e3;
    border-radius: 8px;
    -webkit-box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.05);
    box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.05);
}
</style>

<div class = "row">
    <div class = "col-md-6 col-md-offset-3">
        <h1 class = "text-center">Creat Your Profile!</h1>
        <p class = "text-center">Become part of the worlds greatest premier site for Ninjas and Entrepreneurship.</p>
        <div class="well">
            <%= form_for @profile, url: user_profile_path do |f| %>
                <div class="form-group">
                  <%= f.label :first_name %>
                  <%= f.text_field :first_name, class: 'form-control' %>
                </div>
                <div class="form-group">
                  <%= f.label :last_name %>
                  <%= f.text_field :last_name, class: 'form-control' %>
                </div>
                <div class="form-group">
                  <%= f.label :job_title %>
                  <%= f.select :job_title, ['Ninja', 'Entrepreneur', 'Investor'], {}, class: 'form-control' %>
                </div>
                <div class="form-group">
                  <%= f.label :phone_number %>
                  <%= f.text_field :phone_number, class: 'form-control' %>
                </div>
                <div class="form-group">
                  <%= f.label :contact_email %>
                  <%= f.text_field :contact_email, class: 'form-control' %>
                </div>
                <div class="form-group">
                  <%= f.label :description %>
                  <%= f.text_area :description, class: 'form-control' %>
                </div>
                <div class="form-group">
                  <%= f.submit "Update Profile", class: 'btn btn-warning btn-lg btn-block' %>
                </div>
            <% end %>
        </div>
    </div>
</div>

app/views/users/show.html.erb
<%= @user.profile.first_name %> <%= @user.profile.last_name %>
<%= @user.profile.job_title %><br/>
<% if current_user.plan_id == 2 %>
  <%= @user.profile.phone_number %><br/>
  <%= @user.profile.contact_email %><br/>
<% end %>
<%= @user.profile.description %><br/>